### ISSUE TITLE
Ģiilde

### ISSUE THREAD

**Issue by Ax1leModelling** [Ax1leModelling/ax1le#2]
1. Bugs -ir izveidojot ģildi ( https://prntscr.com/tg8tay ) 
2. Bugs- uzrodās kad ģildi mēģiiini izveidot otro reizii ( https://prntscr.com/tg8tic )
3. Bugs - Izmetas error nomainot attēlu Castle ģildes ( https://prntscr.com/tg8y03 )
4. Bugs - Nevar spiegot ģiildii ( https://prntscr.com/tg91sz )
5. Bugs - Nevar nomaiinīt logo ģildei ( https://prntscr.com/tg92hf )

**Comment by Nauris-kb** [comment]
CLOSE ( ALL FIXED )
