### ISSUE TITLE
Čata piemeslojuums ar sitiena spēku 

### ISSUE THREAD

**Issue by Ax1leModelling** [Ax1leModelling/ax1le#5]
https://prnt.sc/tg9uts

Vēlams noņemt nost

**Comment by Nauris-kb** [comment]
![image](https://user-images.githubusercontent.com/68148253/87246033-17de5d80-c453-11ea-87c3-6be20f1bf983.png)

**Comment by Nauris-kb** [comment]
Parliecināties vai tiešam  gribat lai noņemam
